# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-02 17:33
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
                ('balls', models.CommaSeparatedIntegerField(max_length=255)),
                ('winner', models.NullBooleanField()),
            ],
            options={
                'verbose_name_plural': 'Entries',
            },
        ),
        migrations.CreateModel(
            name='Lottery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('prize', models.CharField(max_length=255)),
                ('number_of_balls', models.PositiveSmallIntegerField(help_text='From 1 - 10', validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(1)])),
                ('max_ball', models.PositiveSmallIntegerField(help_text='From 1 - 100', validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)])),
                ('draw_result', models.CommaSeparatedIntegerField(blank=True, max_length=255, null=True)),
                ('draw_date', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('is_active_from', models.DateTimeField(auto_now_add=True)),
                ('is_closed_from', models.DateTimeField()),
            ],
            options={
                'ordering': ('date_created',),
                'verbose_name_plural': 'Lotteries',
            },
        ),
        migrations.AddField(
            model_name='entry',
            name='entry_for',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Lottery'),
        ),
        migrations.AddField(
            model_name='entry',
            name='entry_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='entry',
            unique_together=set([('entry_for', 'entry_user')]),
        ),
    ]
