# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-02 08:29
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.BaseModel')),
                ('balls', models.CommaSeparatedIntegerField(max_length=255)),
                ('winner', models.NullBooleanField()),
            ],
            bases=('core.basemodel',),
        ),
        migrations.CreateModel(
            name='Lottery',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.BaseModel')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('number_of_balls', models.IntegerField(help_text='From 1 - 10', validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(1)])),
                ('max_ball', models.IntegerField(help_text='From 1 - 100', validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)])),
                ('occurrence', models.IntegerField(default=7)),
                ('next_draw', models.DateTimeField()),
                ('is_active', models.BooleanField(default=False)),
                ('is_active_from', models.DateTimeField(auto_now_add=True)),
            ],
            bases=('core.basemodel',),
        ),
        migrations.AddField(
            model_name='entry',
            name='entry_for',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Lottery'),
        ),
        migrations.AddField(
            model_name='entry',
            name='entry_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='entry',
            unique_together=set([('entry_for', 'entry_user')]),
        ),
    ]
