# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-02 12:38
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lottery',
            old_name='next_draw',
            new_name='is_closed_from',
        ),
        migrations.RemoveField(
            model_name='lottery',
            name='occurrence',
        ),
        migrations.AddField(
            model_name='lottery',
            name='draw_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='lottery',
            name='draw_result',
            field=models.CommaSeparatedIntegerField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='lottery',
            name='max_ball',
            field=models.PositiveSmallIntegerField(help_text='From 1 - 100', validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='lottery',
            name='number_of_balls',
            field=models.PositiveSmallIntegerField(help_text='From 1 - 10', validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(1)]),
        ),
    ]
