# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-03 11:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lottery',
            name='draw_machine',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='lottery',
            name='is_active',
            field=models.BooleanField(default=False, help_text='Display on site'),
        ),
        migrations.AlterField(
            model_name='lottery',
            name='is_active_from',
            field=models.DateTimeField(help_text='When to display on site from'),
        ),
        migrations.AlterField(
            model_name='lottery',
            name='is_closed_from',
            field=models.DateTimeField(help_text='When entries are closed from'),
        ),
    ]
